# REIT STOCK ANALYSIS

In this project, you will analyze Real Estate Investment Trusts, commonly known as REITs. REITs are companies that own or operate real estate that produces income. REITs, like the stocks of regular public companies, are traded on different stock exchanges. Investing in a REIT allows you to invest in portfolios of real estate assets the same way you can invest in a company by buying its stock.

Using financial statistics and NumPy you will analyze two REITs: [Sabra Health Care REIT Inc. (NASDAQ: SBRA)](https://finance.yahoo.com/quote/SBRA/), which invests in health care real estate, and [Equity Residential (NASDAQ:EQR)](https://finance.yahoo.com/quote/EQR/), which invests in rental apartment properties.

The time period for analysis we will be using is `Jan 1 2018` to `Dec 31 2018`. The REIT data for SBRA (`SBRA.csv`) and EQR (`EQR.csv`) can be found in the same folder as this file.

1. Import the numpy module as np

In [1]:
import numpy as np
import pandas as pd

2. Load the adjusted closings for SBRA

In [2]:
SBRA = pd.read_csv('SBRA.csv')
SBRA

Date       Open       High        Low      Close  Adj Close  \
0    2019-01-02  16.320000  16.320000  15.880000  16.070000  15.362330   
1    2019-01-03  16.049999  16.900000  15.930000  16.750000  16.012386   
2    2019-01-04  16.809999  17.340000  16.670000  17.290001  16.528606   
3    2019-01-07  17.340000  17.770000  17.270000  17.660000  16.882313   
4    2019-01-08  17.850000  18.389999  17.600000  18.230000  17.427212   
..          ...        ...        ...        ...        ...        ...   
119  2019-06-24  19.580000  19.670000  19.180000  19.309999  19.309999   
120  2019-06-25  19.379999  19.620001  19.219999  19.260000  19.260000   
121  2019-06-26  19.260000  19.270000  18.790001  18.870001  18.870001   
122  2019-06-27  18.959999  19.480000  18.879999  19.450001  19.450001   
123  2019-06-28  19.469999  19.760000  19.450001  19.690001  19.690001   

      Volume  
0    1697200  
1    2283900  
2    2635900  
3    1858700  
4    2241700  
..       ...  
119  1691000  
120  1678500  
121  1553900  
122  1206600  
123  1999000  

[124 rows x 7 columns]

In [3]:
SBRA_adj = SBRA['Adj Close']
SBRA_adj
                

0      15.362330
1      16.012386
2      16.528606
3      16.882313
4      17.427212
         ...    
119    19.309999
120    19.260000
121    18.870001
122    19.450001
123    19.690001
Name: Adj Close, Length: 124, dtype: float64

3. Load the adjusted closings for EQR

In [4]:
EQR = pd.read_csv('EQR.csv')
EQR

Date       Open       High        Low      Close  Adj Close  \
0    2019-01-02  65.419998  65.430000  63.410000  63.759998  62.800674   
1    2019-01-03  63.669998  65.059998  63.669998  64.160004  63.194660   
2    2019-01-04  64.330002  65.199997  64.160004  64.559998  63.588642   
3    2019-01-07  64.769997  65.559998  64.660004  65.099998  64.120514   
4    2019-01-08  65.330002  66.410004  65.190002  66.320000  65.322166   
..          ...        ...        ...        ...        ...        ...   
119  2019-06-24  78.339996  78.449997  77.709999  78.269997  77.682327   
120  2019-06-25  78.360001  78.760002  76.839996  76.910004  76.332542   
121  2019-06-26  76.839996  76.910004  75.040001  75.650002  75.082001   
122  2019-06-27  75.570000  76.480003  75.260002  75.610001  75.610001   
123  2019-06-28  75.680000  76.660004  75.629997  75.919998  75.919998   

      Volume  
0    1300000  
1    1744700  
2    1462500  
3    1792200  
4    2047900  
..       ...  
119   794300  
120   956000  
121  1558100  
122   876300  
123  1934500  

[124 rows x 7 columns]

In [5]:
EQR_adj = EQR['Adj Close']
EQR_adj

0      62.800674
1      63.194660
2      63.588642
3      64.120514
4      65.322166
         ...    
119    77.682327
120    76.332542
121    75.082001
122    75.610001
123    75.919998
Name: Adj Close, Length: 124, dtype: float64

## Simple Rate of Return Function

4. To calculate the daily rate of return for the SBRA stock, we need the daily adjusted closing price. The formula we are using for the daily rate of return is out[n] = a[n+1] - a[n] 

5. Create a function that returns the daily rate of return

    step 1. define a function named `rate_of_return`
    
    step 2. create parameter for  `adj_closings`
    
    step 3. Within the function use np.diff() and set it to the variable `daily_simple_ror`
    
    step 4. return `daily_simple_ror`

In [6]:
def simple_rate_of_return(adj_closings):
    daily_simple_ror = np.diff(adj_closings)
    return daily_simple_ror

## Calculate Daily Rate of Return for SBRA

6. Call the function `simple_rate_of_return` with the arguments `adj_closings_sbra`. Then print the results. 

In [7]:
SBRA_daily_sror = simple_rate_of_return(SBRA_adj)
SBRA_daily_sror

array([ 0.650056,  0.51622 ,  0.353707,  0.544899,  0.095596, -0.00956 ,
       -0.086036, -0.162514,  0.152954,  0.430184,  0.258111,  0.238991,
       -0.03824 ,  0.191194,  0.277228,  0.31547 ,  0.296346, -0.009558,
        0.181632,  0.076479, -0.210312,  0.23899 , -0.124275,  0.095597,
        0.172071, -0.152954, -0.047796, -0.248553, -0.028677,  0.009777,
        0.205321, -0.156435, -0.146658, -0.019556, -0.078217, -0.508417,
       -0.254208, -0.342201, -0.322649, -0.400867, -0.068442,  0.009779,
       -0.107549, -0.029332, -0.048887,  0.312872,  0.224877,  0.332426,
        0.029329, -0.078217, -0.166214,  0.039111,  0.215099,  0.606188,
       -0.293318,  0.156437,  0.312872,  0.107548,  0.322649, -0.156437,
       -0.136879, -0.019556, -0.185767,  0.068442,  0.195543, -0.087995,
       -0.06844 ,  0.244431,  0.195545,  0.      , -0.019556, -0.400866,
       -0.45953 ,  0.351981, -0.303095,  0.303095,  0.195545,  0.      ,
        0.24443 , -0.185768,  0.156435, -0.029329, 

## Calculate Daily Rate of Return for EQR

7. Call the function `simple_rate_of_return` with the arguments `adj_closings_eqr`. Then print the results. 

In [8]:
EQR_daily_sror = simple_rate_of_return(EQR_adj)
EQR_daily_sror

array([ 0.393986,  0.393982,  0.531872,  1.201652,  0.      ,  1.073601,
        0.137886,  0.078797,  0.817505,  0.610679,  0.817513,  0.20684 ,
        0.275788, -0.059105,  0.009857,  0.315178,  1.03421 ,  0.640221,
       -0.364441,  0.551574, -0.531868,  0.758416,  0.157585,  0.049247,
        0.531884, -0.098496,  0.019692, -0.906151,  0.738708, -0.167434,
        0.088638,  0.315186, -0.837204,  1.162246,  0.364434, -0.719025,
        0.21669 , -0.384125,  0.354584, -0.187149,  0.472786, -0.049256,
       -0.374275, -0.118194,  0.206833,  0.787971,  0.600815, -0.137886,
        0.147735, -0.295478, -0.768265, -0.472786,  0.118202,  1.15239 ,
        0.176666,  0.069473,  0.664971, -0.158799,  0.645119, -0.307671,
       -0.337448,  0.704674, -0.297752, -0.109177,  0.327522, -0.049621,
       -0.168724,  0.952789,  0.337448,  0.754295,  0.148873, -1.855957,
       -1.429192,  0.774147, -0.893249,  0.784073,  0.506172,  0.496246,
        0.228272, -0.893242,  1.111587,  0.099251, 

## Calculate Average Daily Return for SBRA

8. Use `np.mean()` with the argument `daily_simple_returns_sbra` to calculate the average daily return for SBRA. Then set it to the variable name `average_daily_simple_return_sbra`

In [9]:
average_daily_simple_return_SBRA = np.mean(SBRA_daily_sror)
average_daily_simple_return_SBRA

0.03518431707317072

## Calculate Average Daily Return for EQR

9. Use `np.mean()` with the argument `daily_simple_returns_eqr` to calculate the average daily return for EQR. Then set it to the variable name `average_daily_simple_return_eqr`

In [10]:
average_daily_simple_return_EQR = np.mean(EQR_daily_sror)
average_daily_simple_return_EQR

0.10666117073170736

## Compare the Average Daily Return between EQR and SBRA

10. Based on the average daily simple returns of EQR and SBRA, which stock is more likely to be profitable in the future?

### EQR is more profitable

## Daily Log Returns Function

11. Create a function that returns the daily rate of return

    step 1. define a function named log_returns
    
    step 2. create parameter for  `adj_closings`
    
    step 3. use np.log() to get the log of each adjusted closing price and set it to the variable `log_adj_closings`
    
    step 4. use np.diff() to get the diff of each daily log adjusted closing price and set it to the variable `daily_log_returns`
    
    step 5. return `daily_log_returns`

In [11]:
def log_returns(adj_closings):
    log_adj_closings = np.log(adj_closings)
    daily_log_returns = np.diff(log_adj_closings)
    return daily_log_returns

## Calculate Daily Log Returns for SBRA

12. Call the function `log_returns` with the arguments `adj_closings_sbra`. Set it to the variable `daily_log_returns_sbra`. Then print the results. 

In [14]:
daily_log_returns_SBRA = log_returns(SBRA_adj)
daily_log_returns_SBRA

array([ 0.04144414,  0.03173003,  0.02117393,  0.03176639,  0.00547045,
       -0.00054572, -0.00492473, -0.00936905,  0.00882034,  0.02439809,
        0.01435818,  0.01311323, -0.00208667,  0.01038978,  0.01487581,
        0.01666295,  0.01540389, -0.00049313,  0.00932975,  0.00390254,
       -0.01076858,  0.01222804, -0.00633993,  0.00488047,  0.00872509,
       -0.00775197, -0.00243476, -0.01275791, -0.00148248,  0.00050568,
        0.01056078, -0.00803617, -0.00759303, -0.00101686, -0.00407743,
       -0.0269168 , -0.01373503, -0.01879239, -0.0180481 , -0.02288689,
       -0.00396048,  0.00056684, -0.00625177, -0.00171186, -0.00285965,
        0.01816172,  0.01285297,  0.01870243,  0.00163339, -0.00436201,
       -0.0093331 ,  0.00220398,  0.01203516,  0.03315811, -0.01590708,
        0.00851529,  0.01681599,  0.00571571,  0.01695394, -0.00818426,
       -0.00721641, -0.00103528, -0.00988817,  0.00365448,  0.01036808,
       -0.00465237, -0.0036335 ,  0.01291675,  0.01021462,  0.  

## Calculate Daily Log Returns for EQR

13. Call the function `log_returns` with the arguments `adj_closings_eqr`. Set it to the variable `daily_log_returns_eqr`. Then print the results. 

In [13]:
daily_log_returns_EQR = log_returns(EQR_adj)
daily_log_returns_EQR

array([ 0.006254  ,  0.00621507,  0.00832947,  0.01856708,  0.        ,
        0.01630188,  0.00207458,  0.00118362,  0.01219786,  0.00901573,
        0.01194346,  0.00299935,  0.00398522, -0.00085275,  0.00014226,
        0.00453827,  0.01474861,  0.00902221, -0.00512584,  0.00774768,
       -0.00746985,  0.01063474,  0.00219559,  0.00068516,  0.00737016,
       -0.00136074,  0.0002722 , -0.01260281,  0.01028593, -0.00232213,
        0.00122999,  0.00436147, -0.01162714,  0.01610517,  0.00499698,
       -0.00988309,  0.00298873, -0.00530423,  0.00489731, -0.0025818 ,
        0.00650949, -0.0006762 , -0.00515315, -0.00163287,  0.00285568,
        0.01080518,  0.00816103, -0.00186706,  0.00200029, -0.0040047 ,
       -0.01048821, -0.00650949,  0.00163143,  0.01576737,  0.00239537,
        0.0009404 ,  0.0089567 , -0.00213163,  0.00863161, -0.00410731,
       -0.0045243 ,  0.0094247 , -0.00397147, -0.00146018,  0.00437405,
       -0.00066146, -0.00225241,  0.01265335,  0.0044433 ,  0.00

## Annualize Daily Log Return Function

14. Create a function that returns the daily rate of return

    step 1. define a function named `annualize_log_return`
    
    step 2. create parameter for  `daily_log_returns`
    
    step 3. use `np.mean()` with the argument `daily_log_returns` to calculate the average daily return. Then set it to the variable name `average_daily_log_returns`
    
    step 4. then multiply `average_daily_log_returns` by 250 and set it to the variable `annualized_log_return`
    
    step 5. return `annualized_log_return`

In [15]:
def annualize_log_return(daily_log_return):
    average_daily_log_returns = np.mean(daily_log_return)
    annualized_log_return = 250 * average_daily_log_returns
    return annualized_log_return

## Calculate Annualize Daily Log Return for SBRA

10. Call the function `annualize_log_return` with the arguments `daily_log_returns_sbra`. Set it to the variable `annualized_log_return_sbra`. Then print the results. 

In [16]:
annualized_log_return_SBRA = annualize_log_return(daily_log_returns_SBRA)
annualized_log_return_SBRA

0.5044563709645333

## Calculate Annualize Daily Log Return for EQR

11. Call the function `annualize_log_return` with the arguments `daily_log_returns_eqr`. Set it to the variable `annualized_log_return_eqr`. Then print the results. 

In [17]:
annualized_log_return_EQR = annualize_log_return(daily_log_returns_EQR)
annualized_log_return_EQR

0.3855982155640554

## Compare the Annualize Daily Log Return between EQR and SBRA

12. Based on the differences between the Annualize Daily Log Return for EQR and SBRA, Which could be more profitable in the future and why?

### SBRA Has a better annualized rate of return

## Calculate Variance of Daily Log Return for SBRA

13. Calculate the variance of the daily logarithmetic return for SBRA. Use the function `.var()` with the argument `log_daily_ror`. Set it to the variable `daily_varaince_sbra`. Then print the results. 

In [18]:
daily_varaince_SBRA = np.var(daily_log_returns_SBRA)
daily_varaince_SBRA

0.00017844226355047074

## Calculate Variance of Daily Log Return for EQR

14. Calculate the variance of the daily logarithmetic return for EQR. Use the function `.var()` with the argument `daily_log_returns_eqr`. Set it to the variable `daily_varaince_eqr`. Then print the results. 

In [19]:
daily_varaince_EQR = np.var(daily_log_returns_EQR)
daily_varaince_EQR

6.833881310511606e-05

## Compare the Variance of Daily Log Return between EQR and SBRA

15. Explain which investment is more riskier based on the Variance of daily log return between EQR and SBRA ?

### SBRA Has a higher variance and involves more risk

## Calculate the Daily Standard Deviation for SBRA

16. Calculate the Standard Deviation of the daily logarithmetic return for SBRA. Use the function `.std()` with the argument `daily_log_returns_sbra`. Set it to the variable `daily_sd_sbra`. Then print the results. 

In [21]:
daily_varaince_SBRA = np.std(daily_log_returns_SBRA)
daily_varaince_SBRA

0.013358228308816658

## Calculate the Daily Standard Deviation for EQR

17. Calculate the Standard Deviation of the daily logarithmetic return for EQR. Use the function `.std()` with the argument `daily_log_returns_eqr`. Set it to the variable `daily_sd_eqr`. Then print the results. 

In [22]:
daily_varaince_EQR = np.std(daily_log_returns_EQR)
daily_varaince_EQR

0.00826672928703463

## Compare the Daily Standard Deviation between EQR and SBRA

18. Has your previous variance risk assessment changed based on the Daily Standard Deviation and why?

### No, SBRA has a higher standard deviation so still involves more risk

## Calculate the Correlation between SBRA and EQR

19. Calculate the Correlation of the daily logarithmetic return between SBRA and ERQ assets. Use the function `.corrcoef()` with the arguments `daily_log_returns_sbra` and `daily_log_returns_eqr`. Set it to the variable `corr_sbra_eqr`. Then print the results. 

In [23]:
corr_sbra_eqr = np.corrcoef(daily_log_returns_SBRA, daily_log_returns_EQR)
corr_sbra_eqr

array([[1.        , 0.62096591],
       [0.62096591, 1.        ]])

## Interpret the Correlation between SBRA and EQR

20. Interpret and explain the correlation between the stocks SBRA and EQR?

There is a positive correlation between the two stocks meaning they trend in the same directions usually

## Final Analysis

21. Which stock would you invest in based on risk and profitability?

Up for interpretation. I like bigger risk, so I would go with SBRA.